{"@t":"2020-03-31T22:02:26.2237895Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:07:30.2567012Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:12:34.3343516Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":30,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:17:38.3558834Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:22:42.3778828Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:27:46.4001381Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":36,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:32:50.4280495Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":38,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:37:54.4446401Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":30,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:42:58.4616409Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":36,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:48:02.4859987Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:53:06.5069157Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T22:58:10.5211170Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:03:14.5438323Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:08:18.5719032Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":37,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:13:22.5983169Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:18:26.6072184Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:23:30.6362583Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:28:34.6458956Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":40,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:33:38.6783524Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:38:42.6900316Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:43:46.7145247Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":36,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:48:50.7457373Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":35,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:53:54.7722983Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":17,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-03-31T23:58:58.7923371Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":7,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-01T00:04:02.8178208Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":33,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
{"@t":"2020-04-01T00:09:06.8314221Z","@mt":"Keep alive failed (at '{UmbracoAppUrl}').","@l":"Error","@x":"System.Net.Http.HttpRequestException: Ocorreu um erro durante o envio do pedido. ---> System.Net.WebException: Não é possível estabelecer ligação com o servidor remoto ---> System.Net.Sockets.SocketException: Nenhuma ligação pôde ser feita porque o computador de destino\r\nas recusou ativamente 127.0.0.1:80\r\n   em System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   em System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   em System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   em System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n   --- Fim do rastreio da pilha de excepção interna ---\r\n   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   em Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext() em D:\\a\\1\\s\\src\\Umbraco.Web\\Scheduling\\KeepAlive.cs:line 63","UmbracoAppUrl":"http://localhost/umbraco","SourceContext":"Umbraco.Web.Scheduling.KeepAlive","ProcessId":21268,"ProcessName":"iisexpress","ThreadId":36,"AppDomainId":2,"AppDomainAppId":"LMW3SVC2ROOT","MachineName":"DESKTOP-9M7RJNR","Log4NetLevel":"ERROR"}
